os: linux
language: node_js
node_js:
  - 14
branches:
  only:
    - with-keystone
cache:
  directories:
    - node_modules
    - .next
before_script:
  - yarn
  - yarn build
script:
  - yarn gen
deploy:
  provider: pages
  skip_cleanup: true
  token: $GH_TOKEN
  keep_history: true
  on:
    branch: with-keystone
  local_dir: out
  target_branch: gh-pages